<a href="https://colab.research.google.com/github/teighteen44/UTS/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Deteksi penyakit diabetes dengan Deep Learning

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv('./diabetes_latih.csv')

X_train = df.values
X_train = np.delete(X_train,8,axis=1)

y_train = df['Outcome'].values

df = pd.read_csv('./diabetes_uji.csv')

X_test = df.values
X_test = np.delete(X_test,8,axis=1)

y_test = df['Outcome'].values

#df.head()
#print(X_train)

In [7]:
from sklearn.preprocessing import MinMaxScaler

X_train = MinMaxScaler().fit_transform(X_train)
X_test = MinMaxScaler().fit_transform(X_test)

print(X_train)

[[0.47058824 0.94472362 0.68421053 ... 0.71385991 0.02519214 0.36666667]
 [0.41176471 0.7638191  0.77192982 ... 0.74515648 0.11058924 0.25      ]
 [0.11764706 0.49748744 0.45614035 ... 0.36661699 0.23868488 0.        ]
 ...
 [0.29411765 0.6080402  0.63157895 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.52631579 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.61403509 ... 0.45305514 0.10119556 0.03333333]]


In [8]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=3,learning_rate_init=0.1,max_iter=100)

clf.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)

In [9]:
y_pred = clf.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score

round(accuracy_score(y_test,y_pred),3)

0.688

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               154 non-null    int64  
 1   Glucose                   154 non-null    int64  
 2   BloodPressure             154 non-null    int64  
 3   SkinThickness             154 non-null    int64  
 4   Insulin                   154 non-null    int64  
 5   BMI                       154 non-null    float64
 6   DiabetesPedigreeFunction  154 non-null    float64
 7   Age                       154 non-null    int64  
 8   Outcome                   154 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 11.0 KB
